name: PFFP_Analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - brotli=1.1.0=h2466b09_2
  - brotli-bin=1.1.0=h2466b09_2
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2024.8.30=h56e8100_0
  - cairo=1.18.0=h32b962e_3
  - certifi=2024.8.30=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.3.0=py312hd5eb7cc_1
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.5=py312h275cf98_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - double-conversion=3.3.0=h63175ca_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.3=he0c23c2_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1=py312h4389bb4_1
  - freetype=2.12.1=hdaf720e_2
  - graphite2=1.3.13=h63175ca_1003
  - harfbuzz=9.0.0=h2bedf89_1
  - icu=75.1=he0c23c2_0
  - importlib-metadata=8.4.0=pyha770c72_0
  - importlib_metadata=8.4.0=hd8ed1ab_0
  - importlib_resources=6.4.4=pyhd8ed1ab_0
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.27.0=pyh7428d3b_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312h2e8e312_0
  - kiwisolver=1.4.7=py312hd5eb7cc_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=h67d730c_0
  - lerc=4.0.0=h63175ca_0
  - libblas=3.9.0=23_win64_mkl
  - libbrotlicommon=1.1.0=h2466b09_2
  - libbrotlidec=1.1.0=h2466b09_2
  - libbrotlienc=1.1.0=h2466b09_2
  - libcblas=3.9.0=23_win64_mkl
  - libclang13=18.1.8=default_ha5278ca_4
  - libdeflate=1.21=h2466b09_0
  - libexpat=2.6.3=he0c23c2_0
  - libffi=3.4.2=h8ffe710_5
  - libglib=2.80.3=h7025463_2
  - libhwloc=2.11.1=default_h8125262_1000
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - liblapack=3.9.0=23_win64_mkl
  - libpng=1.6.43=h19919ed_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.46.1=h2466b09_0
  - libtiff=4.6.0=hb151862_4
  - libwebp-base=1.4.0=hcfcfb64_0
  - libxcb=1.16=h013a479_1
  - libxml2=2.12.7=h0f24e4e_4
  - libxslt=1.1.39=h3df6e99_0
  - libzlib=1.3.1=h2466b09_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib=3.9.2=py312h2e8e312_0
  - matplotlib-base=3.9.2=py312h90004f6_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2024.1.0=h66d3029_694
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbformat=5.10.4=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy=2.1.0=py312h49bc9c5_1
  - openjpeg=2.5.2=h3d672ee_0
  - openpyxl=3.1.5=py312he70551f_1
  - openssl=3.3.2=h2466b09_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py312h72972c8_1
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.44=h3d7b363_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py312h381445a_0
  - pip=24.2=pyh8b19718_1
  - pixman=0.43.4=h63175ca_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.2=pyhd8ed1ab_0
  - plotly=5.24.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=6.0.0=py312h4389bb4_1
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyside6=6.7.2=py312h2ee7485_2
  - python=3.12.5=h889d299_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - pywin32=306=py312h53d5487_2
  - pyzmq=26.2.0=py312hd7027bb_2
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.7.2=hbb46ec1_5
  - referencing=0.35.1=pyhd8ed1ab_0
  - rpds-py=0.20.0=py312h2615798_1
  - scipy=1.14.1=py312h1f4e10d_0
  - setuptools=73.0.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.13.0=hc790b64_0
  - tenacity=9.0.0=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - tornado=6.4.1=py312h4389bb4_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h8827d51_1
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.3=h8a93ad2_20
  - vc14_runtime=14.40.33810=hcc2c482_20
  - vs2015_runtime=14.40.33810=h3bf8584_20
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - zeromq=4.3.5=he1f189c_5
  - zipp=3.20.1=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_1
  - zstd=1.5.6=h0ea2cb4_0
prefix: C:\Users\johnm\anaconda3\envs\PFFP_Analysis
